# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='igbd_url',
            field=models.TextField(blank=True),
        ),
    ]
