# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20171204_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
