# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20171204_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.Game'),
        ),
    ]
