# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
